<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <AnalysisLevel>latest</AnalysisLevel>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <Company>IronTrace</Company>
    <Product>IronTrace</Product>
    <Authors>IronTrace</Authors>
    <Copyright>Copyright (c) 2026 IronTrace</Copyright>
    <Version>0.6.0</Version>
    <AssemblyVersion>0.6.0.0</AssemblyVersion>
    <FileVersion>0.6.0.0</FileVersion>
    <NeutralLanguage>en</NeutralLanguage>
  </PropertyGroup>
</Project>
